In [1]:
import yaml
import torch

In [2]:
learning_params_file = "src/CoverageControl/params/learning_params.yaml"
data_params_file = "src/CoverageControl/params/data_params.yaml"

In [3]:
with open(learning_params_file, 'r') as stream:
    l_config = yaml.safe_load(stream)
print(l_config)

{'pDataDir': '/root/CoverageControl_ws/data/pure_coverage/', 'GPUs': [4, 5], 'ModelConfig': {'UseCommMaps': True}, 'GNNBackBone': {'InputDim': 7, 'NumHops': 3, 'NumLayers': 4, 'LatentSize': 64, 'OutputDim': 2}, 'GNNTraining': {'LearningRate': 0.001, 'WeightDecay': 0.0001, 'BatchSize': 10, 'NumEpochs': 50}, 'CNN': {'InputDim': 4, 'OutputDim': 7, 'NumLayers': 2, 'LatentSize': 8, 'KernelSize': 3, 'ImageSize': 32}, 'CNNTraining': {'LearningRate': 0.001, 'WeightDecay': 0.0001, 'BatchSize': 10, 'NumEpochs': 50}}


In [5]:
l_config['ModelConfig']['UseCommMaps']

True

In [10]:
class A:
    def test(self):
        print("a")
        
class B(A):
    def atest(self):
        print("b")
        self.test()

obj = B()
obj.atest()

b
a


In [17]:
a = torch.rand(3, 2, 5)
print(a)
a[:,:, :1]

tensor([[[0.5665, 0.8053, 0.6683, 0.2149, 0.7278],
         [0.8847, 0.1188, 0.9666, 0.6405, 0.5855]],

        [[0.3149, 0.3926, 0.4127, 0.8486, 0.6573],
         [0.7912, 0.4457, 0.4468, 0.2170, 0.7036]],

        [[0.8541, 0.2796, 0.3115, 0.3510, 0.7197],
         [0.7870, 0.4487, 0.7418, 0.9296, 0.5215]]])


tensor([[[0.5665],
         [0.8847]],

        [[0.3149],
         [0.7912]],

        [[0.8541],
         [0.7870]]])

In [26]:
cnn_model = torch.jit.load('data/cnn/data/model.pt')
print(cnn_model)

RecursiveScriptModule(
  original_name=Module
  (cnn_backbone): RecursiveScriptModule(
    original_name=Module
    (conv0): RecursiveScriptModule(original_name=Module)
    (batch_norm0): RecursiveScriptModule(original_name=Module)
    (conv1): RecursiveScriptModule(original_name=Module)
    (batch_norm1): RecursiveScriptModule(original_name=Module)
    (conv2): RecursiveScriptModule(original_name=Module)
    (batch_norm2): RecursiveScriptModule(original_name=Module)
    (conv3): RecursiveScriptModule(original_name=Module)
    (batch_norm3): RecursiveScriptModule(original_name=Module)
    (conv4): RecursiveScriptModule(original_name=Module)
    (batch_norm4): RecursiveScriptModule(original_name=Module)
    (linear_1): RecursiveScriptModule(original_name=Module)
    (linear_2): RecursiveScriptModule(original_name=Module)
    (linear_3): RecursiveScriptModule(original_name=Module)
  )
  (linear): RecursiveScriptModule(original_name=Module)
)


In [38]:
keys = list(cnn_model.state_dict().keys())
print(keys)

['cnn_backbone.conv0.weight', 'cnn_backbone.conv0.bias', 'cnn_backbone.batch_norm0.weight', 'cnn_backbone.batch_norm0.bias', 'cnn_backbone.batch_norm0.running_mean', 'cnn_backbone.batch_norm0.running_var', 'cnn_backbone.batch_norm0.num_batches_tracked', 'cnn_backbone.conv1.weight', 'cnn_backbone.conv1.bias', 'cnn_backbone.batch_norm1.weight', 'cnn_backbone.batch_norm1.bias', 'cnn_backbone.batch_norm1.running_mean', 'cnn_backbone.batch_norm1.running_var', 'cnn_backbone.batch_norm1.num_batches_tracked', 'cnn_backbone.conv2.weight', 'cnn_backbone.conv2.bias', 'cnn_backbone.batch_norm2.weight', 'cnn_backbone.batch_norm2.bias', 'cnn_backbone.batch_norm2.running_mean', 'cnn_backbone.batch_norm2.running_var', 'cnn_backbone.batch_norm2.num_batches_tracked', 'cnn_backbone.conv3.weight', 'cnn_backbone.conv3.bias', 'cnn_backbone.batch_norm3.weight', 'cnn_backbone.batch_norm3.bias', 'cnn_backbone.batch_norm3.running_mean', 'cnn_backbone.batch_norm3.running_var', 'cnn_backbone.batch_norm3.num_batch

In [84]:
cnn_model.state_dict()['linear.bias'].shape

torch.Size([7])

In [41]:
len(list(cnn_model.parameters()))

28

In [31]:
a = torch.rand(5, 4, 32, 32)
cnn_model.cnn_backbone(a)


AttributeError: 'RecursiveScriptModule' object has no attribute 'forward'

In [25]:
print(cnn_model)

RecursiveScriptModule(
  original_name=Module
  (cnn_backbone): RecursiveScriptModule(
    original_name=Module
    (conv0): RecursiveScriptModule(original_name=Module)
    (batch_norm0): RecursiveScriptModule(original_name=Module)
    (conv1): RecursiveScriptModule(original_name=Module)
    (batch_norm1): RecursiveScriptModule(original_name=Module)
    (conv2): RecursiveScriptModule(original_name=Module)
    (batch_norm2): RecursiveScriptModule(original_name=Module)
    (conv3): RecursiveScriptModule(original_name=Module)
    (batch_norm3): RecursiveScriptModule(original_name=Module)
    (conv4): RecursiveScriptModule(original_name=Module)
    (batch_norm4): RecursiveScriptModule(original_name=Module)
    (linear_1): RecursiveScriptModule(original_name=Module)
    (linear_2): RecursiveScriptModule(original_name=Module)
    (linear_3): RecursiveScriptModule(original_name=Module)
  )
  (linear): RecursiveScriptModule(original_name=Module)
)


In [78]:
mm = torch.nn.ModuleList()
mm1 = torch.nn.Conv2d(10,10, kernel_size=2)
mm.add_module("conv", mm1)
del(mm1)

In [76]:
list(mm.parameters())

[Parameter containing:
 tensor([[[[-0.0328,  0.1050],
           [-0.1347, -0.0835]],
 
          [[ 0.0720, -0.0565],
           [ 0.0071, -0.0732]],
 
          [[ 0.1562, -0.0313],
           [ 0.0741,  0.1401]],
 
          [[-0.1270, -0.0763],
           [ 0.0561, -0.0272]],
 
          [[ 0.1409, -0.0785],
           [-0.0617,  0.1040]],
 
          [[-0.1573,  0.0532],
           [ 0.1209,  0.1140]],
 
          [[ 0.1226, -0.0746],
           [ 0.1443,  0.1449]],
 
          [[-0.1284, -0.1267],
           [ 0.0914, -0.0827]],
 
          [[-0.1516, -0.0859],
           [ 0.1410, -0.0152]],
 
          [[-0.0214,  0.1344],
           [-0.0204,  0.0762]]],
 
 
         [[[-0.0329, -0.0348],
           [-0.0381,  0.0806]],
 
          [[-0.1406, -0.0998],
           [-0.1311,  0.0217]],
 
          [[ 0.0374,  0.0902],
           [-0.1478, -0.0014]],
 
          [[-0.1255,  0.1572],
           [ 0.0993,  0.0347]],
 
          [[-0.0585,  0.0656],
           [ 0.0369, -0.0523]],
 

In [81]:
mm.state_dict()

OrderedDict([('conv.weight',
              tensor([[[[-4.8091e-02,  1.0518e-01],
                        [-2.0030e-02,  3.6652e-02]],
              
                       [[-1.1777e-01, -8.3392e-02],
                        [ 1.3422e-01, -1.0751e-01]],
              
                       [[ 1.0854e-01, -1.1357e-01],
                        [-6.4001e-02,  9.8345e-02]],
              
                       [[-8.3312e-02, -6.0701e-03],
                        [ 1.0738e-01, -1.0416e-01]],
              
                       [[-9.9080e-02, -1.3716e-01],
                        [ 1.2989e-01,  3.3842e-02]],
              
                       [[-9.7357e-02, -5.7117e-02],
                        [ 1.1811e-01,  1.2447e-01]],
              
                       [[ 1.2357e-01,  1.0742e-01],
                        [-7.2397e-02,  1.2299e-02]],
              
                       [[-1.8848e-02,  1.4979e-01],
                        [ 5.9200e-02,  1.7403e-03]],
              
           